# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GBShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GBShop
  pod 'Alamofire'
  pod 'Swinject'
  pod 'Firebase/Analytics'

  target 'GBShopTests' do
    inherit! :search_paths
    pod 'Firebase/Analytics'
    # Pods for testing
  end

  target 'GBShopUITests' do
    inherit! :search_paths
    use_frameworks!
    # Pods for testing
    pod 'Alamofire'
    pod 'Swinject'
    pod 'Firebase/Analytics'
    #project '../GBShop/GBShop/GBShop'
  end

end
